version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python sparta_accounts_manager/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/sparta_accounts_manager
    ports:
      - "8000:8000"
    depends_on:
      - db
